name: SageMaker Tests

# All tests in this file:
# 1. Run when launched manually
# 2. Require AWS credentials and launch training jobs

on:
  workflow_dispatch:
#  pull_request: # UNCOMMENT FOR TESTING
#    branches:   # UNCOMMENT FOR TESTING
#      - main    # UNCOMMENT FOR TESTING
#      - dev     # UNCOMMENT FOR TESTING

env:
  AWS_DEFAULT_REGION: us-west-2
  AWS_ROLE: ${{ secrets.PROD_AWS_END_TO_END_TEST_ROLE_ARN }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  launch-sagemaker-jobs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'
    - name: Install Renate
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e '.[dev]'
    - name: Install toml library
      run: pip install toml
    - name: Write requirements.txt for SageMaker training jobs
      run: |
        python test/integration_tests/generate_requirements.py
    - name: Get Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.PROD_AWS_END_TO_END_TEST_ROLE_ARN }}
        role-session-name: integtestsession
        aws-region: ${{ env.AWS_DEFAULT_REGION }}
    - name: Launch SageMaker Jobs
      run: |
        import os
        import subprocess
        
        target_directory = 'test/integration_tests/configs/suites/main'
        files = [f for f in os.listdir(target_directory) if os.path.isfile(os.path.join(target_directory, f))]
        
        for file in files:
          process = subprocess.Popen(
            [
              "python",
              "test/integration_tests/run_test.py",
              "--test-file",
              file,
              "--seed",
              "0",
              "--requirements-file",
              "test/integration_tests/requirements.txt",
            ]
          )
        process.wait()

      shell: python
